<a href="https://colab.research.google.com/github/veeranna-spec/23CSBTB27/blob/main/lab8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
diabetes_data = load_diabetes()

# Convert the 'Bunch' object to a Pandas DataFrame
diabetes_df = pd.DataFrame(diabetes_data.data, columns=diabetes_data.feature_names)
diabetes_df['target'] = diabetes_data.target

# View the first few rows of the DataFrame
diabetes_df.head()

# Split dataset into features and target variable
diabetes_cols = ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']  # Features
X = diabetes_df[diabetes_cols]  # Features
y = diabetes_df['target']  # Target variable

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# Instantiate the Logistic Regression model
logreg = LogisticRegression(solver='liblinear')

# Fit the model with data
logreg.fit(X_train, y_train)

# Predict using the test data
y_pred = logreg.predict(X_test)

# Confusion matrix
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)

# Print confusion matrix, accuracy, precision, and recall
print("Confusion Matrix:\n", cnf_matrix)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred, average='weighted'))  # Change is here
print("Recall:", metrics.recall_score(y_test, y_pred, average='weighted'))  # Change is here


Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy: 0.009009009009009009
Precision: 0.00022522522522522523
Recall: 0.009009009009009009


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
